#!/bin/bash

# This scripts load all combinations for the 2 classes tests

python hoj_gen.py -bo -bop 'tmp_data/2_classes_set/' -bon '3d_points_global_2_classes' -3d -iT

python hoj_gen.py -bo -bop 'tmp_data/2_classes_set/' -bon '3d_points_local_2_classes' -3d -iT -loCoord

python hoj_gen.py -bo -bop 'tmp_data/2_classes_set/' -bon 'hoj_2_classes' -hoj -iT 

python hoj_gen.py -bo -bop 'tmp_data/2_classes_set/' -bon 'hoj_parts_2_classes' -hoj -iT -bP

python hoj_gen.py -bo -bop 'tmp_data/2_classes_set/' -bon 'hoj_cylinder_2_classes' -hoj -iT -dM 'cylinder'

python hoj_gen.py -bo -bop 'tmp_data/2_classes_set/' -bon 'hoj_cylinder_parts_2_classes' -hoj -iT -dM 'cylinder' -bP

python hoj_gen.py -bo -bop 'tmp_data/2_classes_set/' -bon 'hoj_sphere_2_classes' -hoj -iT -dM 'sphere'

python hoj_gen.py -bo -bop 'tmp_data/2_classes_set/' -bon 'hoj_sphere_parts_2_classes' -hoj -iT -dM 'sphere' -bP
