#!/bin/bash

# This scripts load all combinations for the 60 classes tests


python hoj_gen.py -bo -bop 'tmp_data/full_data_set/' -bon '3d_points_global_60_classes' -3d -iT

python hoj_gen.py -bo -bop 'tmp_data/full_data_set/' -bon '3d_points_local_60_classes' -3d -iT -loCoord

python hoj_gen.py -bo -bop 'tmp_data/full_data_set/' -bon 'hoj_60_classes' -hoj -iT 

python hoj_gen.py -bo -bop 'tmp_data/full_data_set/' -bon 'hoj_parts_60_classes' -hoj -iT -bP

python hoj_gen.py -bo -bop 'tmp_data/full_data_set/' -bon 'hoj_cylinder_60_classes' -hoj -iT -dM 'cylinder'

python hoj_gen.py -bo -bop 'tmp_data/full_data_set/' -bon 'hoj_cylinder_parts_60_classes' -hoj -iT -dM 'cylinder' -bP

python hoj_gen.py -bo -bop 'tmp_data/full_data_set/' -bon 'hoj_sphere_60_classes' -hoj -iT -dM 'sphere'

python hoj_gen.py -bo -bop 'tmp_data/full_data_set/' -bon 'hoj_sphere_parts_60_classes' -hoj -iT -dM 'sphere' -bP